### ISSUE TITLE
Sharing Information on Writing Inline Comments within Jinja Templates

### ISSUE THREAD

**Issue by campbellmarianna** [MakeMeSenpai/first_django#1]
Hi Anthony,

You demonstrated proper usage of an inline comment within a Jinja template on line 5 of the index page:

`{# <!-- our html --> #}` 

Similar to what you stated in the README (a comment in the template causes an error in the program),  this is because a comment cannot be created within a `{{ ... }}` statement. In this case the comment starting on line 9 is within a statement starting on line 8 and as a result, will raise an error.

`
...
{% for question in latest_question_list %}
        {# 
        
         #}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
{% endfor %}
...
`

Credit Resource: https://stackoverflow.com/questions/13562222/jinja2-inline-comments

**Comment by The1stAnthony** [comment]
Thank you! Hope it works now. But I will look further into it for clarification.
